name: AML
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - mne
  - pyedflib
  - requests
  - wget
  - pre-commit
